---
- name: "Add repository and install: {{ item.name }}"
  become: true
  tags: repo
  block:
    - name: "Add repository: {{ item.name }}"
      ansible.builtin.deb822_repository:
        name: "{{ item.name }}"
        types: deb
        uris: "{{ item.uris }}"
        suites: "{{ item.suites }}"
        components: "{{ item.components }}"
        architectures: "{{ dpkg_arch.stdout }}"
        signed_by: "{{ item.gpg_key_url }}"

    - name: "Install package: {{ item.name }}"
      ansible.builtin.apt:
        name: "{{ item.name }}"
        state: present
        update_cache: true
