- hosts: localhost
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    personal: "{{ lookup('env', 'HOME') }}/personal"
    user: "jacob"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - name:
      include_tasks:
        file: tasks/ssh-setup.yml
    - name:
      include_tasks:
        file: tasks/git-setup.yml
    - name:
      include_tasks:
        file: tasks/core-setup.yml
    - name:
      include_tasks:
        file: tasks/docker-setup.yml
    # - name:
    #   include_tasks:
    #     file: tasks/asdf-setup.yml
    # - name:
    #   include_tasks:
    #     file: tasks/npm-packages.yml
    - name:
      include_tasks:
        file: tasks/zsh-setup.yml
    # - name:
    #   include_tasks:
    #     file: tasks/slack-setup.yml
    # - name:
    #   include_tasks:
    #     file: tasks/spotify-setup.yml
    # - name:
    #   include_tasks:
    #     file: tasks/personal-projects.yml
    # - name:
    #   include_tasks:
    #     file: tasks/nvim-setup.yml
    # - name:
    #   include_tasks:
    #     file: tasks/brave.yml
    - name:
      include_tasks:
        file: tasks/dotfiles.yml
    - name:
      include_tasks:
        file: tasks/productivity-tools.yml
    - name:
      include_tasks:
        file: tasks/lsp.yml

