---
- name: Provision Ubuntu desktop
  hosts: localhost

  pre_tasks:
    - name: Update apt cache
      become: true
      ansible.builtin.apt:
        update_cache: true
      tags: always

  roles:
    - ssh
    - git
    - fonts
    - core
    - docker
    - zsh
    - mise
    - dotfiles
    - personal_projects
    - deb_packages
    - repo_packages
