- hosts: localhost
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    personal: "{{ lookup('env', 'HOME') }}/repos/personal"
    user: "jacob"
    github_account: "Japenner"
    apt_packages:
      core:
        - build-essential
        - cmake
        - pkg-config
        - libpthread-stubs0-dev
        - lua5.1
        - unzip
        - libtool
        - libtool-bin
        - gettext
        - compton
        - curl
        - htop
        - golang
        - lsof
        - ccache
        - ninja-build
        - python3-pip
        - dconf-editor
        - nvidia-settings
        - moreutils
        - clangd
        - openssl
        - gnupg
        - libpq-dev
        - ca-certificates
        - stow
        - apt-transport-https
        - software-properties-common
      productivity:
        - tmux
        - wireshark
        - fzf
        - xclip
        - tldr
        - ripgrep
        - code
        - shutter
        - gh
    docker_packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    zsh_plugins:
      - name: zsh-autosuggestions
        repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
      - name: zsh-completions
        repo: "https://github.com/zsh-users/zsh-completions.git"
      - name: zsh-syntax-highlighting
        repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    zsh_themes:
      - name: powerlevel10k
        repo: "https://github.com/romkatv/powerlevel10k.git"
    project_repos:
      - anki
      - jacobs_toolbox
      - jp_com
      - obsidian
      - project_ideas
      - yt_dlp_wrapper
    deb_packages:
      - name: rustdesk
        url: "https://github.com/rustdesk/rustdesk/releases/download/1.3.5/rustdesk-1.3.5-x86_64.deb"
        version: "1.3.5"
        arch: "x86_64"
      - name: discord
        url: "https://discord.com/api/download?platform=linux&format=deb"
        version: "latest"
        arch: "amd64"
      - name: obsidian
        url: "https://github.com/obsidianmd/obsidian-releases/releases/download/v1.7.7/obsidian_1.7.7_amd64.deb"
        version: "1.7.7"
        arch: "amd64"
    repo_packages:
      - name: slack
        gpg_key_url: "https://packagecloud.io/slacktechnologies/slack/gpgkey"
        repo: "https://packagecloud.io/slacktechnologies/slack/debian/"
        build: jessie
        branch: main
      - name: signal-desktop
        gpg_key_url: "https://updates.signal.org/desktop/apt/keys.asc"
        repo: "https://updates.signal.org/desktop/apt"
        build: stable
        branch: main
      - name: brave-browser
        gpg_key_url: "https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg"
        repo: "https://brave-browser-apt-release.s3.brave.com/"
        build: stable
        branch: main
    pre_tasks:
      - name: Update Apt
        become: true
        apt:
          update_cache: true
          state: present
        tags: install

  tasks:
    - name: SSH Setup
      include_tasks: tasks/ubuntu/ssh-setup.yml

    - name: Git Setup
      include_tasks: tasks/ubuntu/git-setup.yml

    - name: FiraCode Mono Nerd Font Setup
      include_tasks: tasks/ubuntu/fonts-setup.yml

    - name: Install Core and Productivity Packages
      include_tasks: tasks/ubuntu/core-setup.yml

    - name: Docker Setup
      include_tasks: tasks/ubuntu/docker-setup.yml

    - name: ZSH and Oh-My-Zsh Setup
      include_tasks: tasks/ubuntu/zsh-setup.yml

    - name: ASDF Version Manager Setup
      include_tasks: tasks/ubuntu/asdf-setup.yml

    - name: Dotfiles Setup
      include_tasks: tasks/ubuntu/dotfiles-setup.yml

    - name: Git Clone and Update Personal Projects
      include_tasks: tasks/ubuntu/personal-projects.yml

    - name: Install .deb Packages
      include_tasks: tasks/ubuntu/deb-package-setup.yml
      with_items: "{{ deb_packages }}"

    - name: Install Repository Only Packages
      include_tasks: tasks/ubuntu/repo-package-setup.yml
      with_items: "{{ repo_packages }}"
