- name: Install ASDF dependencies
  become: true
  apt:
    update_cache: true
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - git
  tags: &tags_for_asdf_tasks [ 'install', 'asdf', 'node', 'ruby']

- name: Clone ASDF
  ansible.builtin.git:
    repo: 'https://github.com/asdf-vm/asdf.git'
    dest: "{{ lookup('env', 'HOME') }}/.asdf"
  tags: *tags_for_asdf_tasks

- name: Add asdf to ~/.bashrc
  become: true
  shell: echo ". \"$HOME/.asdf/asdf.sh\"" >> ~/.zshrc
  tags: *tags_for_asdf_tasks

- name: Add asdf completions to fpath
  become: true
  block:
    - name: Append completions to fpath
      shell: |
        echo "# append completions to fpath
        fpath=(${ASDF_DIR}/completions \$fpath)
        # initialise completions with ZSH's compinit
        autoload -Uz compinit && compinit" >> ~/.zshrc
  tags: *tags_for_asdf_tasks

- name: Source .zshrc
  become: true
  shell: source ~/.zshrc
  args:
    executable: /bin/zsh
  tags: *tags_for_asdf_tasks

- name: Add Ruby plugin
  become: true
  shell: asdf plugin add ruby https://github.com/asdf-vm/asdf-ruby.git
  tags: *tags_for_asdf_tasks

- name: Install required libs for Ruby
  become: true
  apt:
    update_cache: true
    name: libyaml-dev
    state: present
  tags: *tags_for_asdf_tasks

- name: Add Node.js plugin
  become: true
  shell: asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
  tags: *tags_for_asdf_tasks


