- name: Install ASDF dependencies
  become: true
  apt:
    name: ["curl", "git"]
  tags:
    - install
    - asdf
    - node
    - ruby

- name: Clone ASDF
  ansible.builtin.git:
    repo: 'https://github.com/asdf-vm/asdf.git'
    dest: "{{ lookup('env', 'HOME') }}/.asdf"
  tags:
    - install
    - asdf
    - node
    - ruby

# Add Ruby plugin:
# asdf plugin add ruby https://github.com/asdf-vm/asdf-ruby.git

# install required libs for ruby:
# sudo apt update && apt install -y libyaml-dev

# Add Nodejs plugin:
# asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
