- name: Install System Packages
  become: true
  apt:
    update_cache: true
    name: "{{ item }}"
    state: present
  loop:
    - build-essential
    - cmake
    - pkg-config
    - libpthread-stubs0-dev
    - lua5.1
    - unzip
    - libtool
    - libtool-bin
    - gettext
    - compton
    - curl
    - htop
    - golang
    - lsof
    - ccache
    - ninja-build
    - python3-pip
    - dconf-editor
    - nvidia-settings
    - moreutils
    - clangd
  tags:
    - install
    - core
