- name: Installing stow
  become: true
  apt:
    name: stow
  tags: &dotfiles_setup_tags [ 'install', 'dotfiles', 'stow' ]

- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: "git@github.com:{{ github_account }}/.dotfiles.git"
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags: *dotfiles_setup_tags

- name: Stow dotfiles
  shell: "cd {{ lookup('env', 'HOME') }}/.dotfiles && ./ubuntu"
  tags: *dotfiles_setup_tags
