- name: Clone or update personal projects
  become: true
  vars:
    personal_projects:
      - name: jp_com
        repo: "git@github.com:{{ github_account }}/jp_com.git"
      - name: obsidian 
        repo: "git@github.com:{{ github_account }}/obsidian.git"
      - name: docker 
        repo: "git@github.com:{{ github_account }}/homelab.git"
  tags: &tags_for_project_tasks [ 'dotfiles', 'install', 'personal-project' ]

- name: Check if project {{ item.name }} exists
  stat:
    path: "{{ personal }}/{{ item.name }}"
  register: project_exists
  loop: "{{ personal_projects }}"
  tags: *tags_for_project_tasks

- name: Clone or update project {{ item.name }}
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ personal }}/{{ item.name }}"
  when: project_exists.stat.exists == False
  loop: "{{ personal_projects }}"
  tags: *tags_for_project_tasks

- name: Checkout master branch for project {{ item.name }}
  shell: "cd {{ personal }}/{{ item.name }} && git fetch && git worktree add master master"
  when: project_exists.stat.exists == False
  loop: "{{ personal_projects }}"
  tags: *tags_for_project_tasks
