- name: jp_com exists
  stat:
    path: "{{ personal }}/jp_com"
  register: jp_com
  tags: &tags_for_project_tasks [ 'dotfiles', 'install', 'personal-project' ]

- name: Personal Project jp_com
  ansible.builtin.git:
    repo: "git@github.com:{{ github_account }}/jp_com.git"
    bare: true
    dest: "{{ personal }}/jp_com"
  tags: *tags_for_project_tasks
  when: jp_com.stat.exists == False

- name: jp_com Master Checkout
  shell: "cd {{ personal }}/jp_com && git fetch && git worktree add master master"
  tags: *tags_for_project_tasks
  when: jp_com.stat.exists == False

- name: obsidian exists
  stat:
    path: "{{ personal }}/obsidian"
  register: obsidian
  tags: *tags_for_project_tasks

- name: Personal Project obsidian
  ansible.builtin.git:
    repo: "git@github.com:{{ github_account }}/obsidian.git"
    bare: true
    dest: "{{ personal }}/obsidian"
  tags: *tags_for_project_tasks
  when: obsidian.stat.exists == False

- name: obsidian Master Checkout
  shell: "cd {{ personal }}/obsidian && git fetch && git worktree add master master"
  tags: *tags_for_project_tasks
  when: obsidian.stat.exists == False

- name: homelab exists
  stat:
    path: "{{ personal }}/docker"
  register: homelab
  tags: *tags_for_project_tasks

- name: Personal Project homelab
  ansible.builtin.git:
    repo: "git@github.com:{{ github_account }}/homelab.git"
    bare: true
    dest: "{{ personal }}/docker"
  tags: *tags_for_project_tasks
  when: homelab.stat.exists == False

- name: homelab Master Checkout
  shell: "cd {{ personal }}/docker && git fetch && git worktree add master master"
  tags: *tags_for_project_tasks
  when: homelab.stat.exists == False

