- name: kdenlive ppa (ppa:kdenlive/kdenlive-stable)
  become: true
  apt_repository:
    repo: ppa:kdenlive/kdenlive-stable
    state: present
    update_cache: True
  tags: &productivity_tags ["install", "productivity"]

- name: shutter ppa (ppa:linuxuprising/shutter)
  become: true
  apt_repository:
    repo: ppa:linuxuprising/shutter
    state: present
    update_cache: True
  tags: *productivity_tags

- name: Install packages
  become: true
  apt:
    update_cache: true
    name: "{{ item }}"
    state: present
  loop:
    - tmux
    - wireshark
    - fzf
    - xclip
    - tldr
    - ripgrep
    # - lazydocker
  tags: &productivity_tags ["install", "productivity"]
