---
- name: Install core and productivity packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    name: "{{ apt_packages.core + apt_packages.productivity }}"
    state: present
  tags:
    - core
    - productivity

- name: Check for NVIDIA GPU
  ansible.builtin.shell: lspci | grep -i nvidia
  register: nvidia_check
  changed_when: false
  failed_when: false
  tags: core

- name: Install nvidia-settings if NVIDIA GPU present
  become: true
  ansible.builtin.apt:
    name: nvidia-settings
    state: present
  when: nvidia_check.rc == 0
  tags: core
