- name: Clone ASDF and configure
  ansible.builtin.git:
    repo: "https://github.com/asdf-vm/asdf.git"
    dest: "{{ lookup('env', 'HOME') }}/.asdf"
    depth: 1
  tags: asdf

- name: Add ASDF plugin for Ruby
  shell: asdf plugin-add ruby https://github.com/asdf-vm/asdf-ruby.git
  args:
    creates: "{{ lookup('env', 'HOME') }}/.asdf/plugins/ruby"
  tags: asdf

- name: Add ASDF plugin for Node.js
  shell: . $HOME/.asdf/asdf.sh && asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git
  args:
    creates: "{{ lookup('env', 'HOME') }}/.asdf/plugins/nodejs"
  environment:
    PATH: "{{ lookup('env', 'PATH') }}:{{ lookup('env', 'HOME') }}/.asdf/bin:{{ lookup('env', 'HOME') }}/.asdf/shims"
  tags: asdf

- name: Add ASDF plugin for Python
  shell: . $HOME/.asdf/asdf.sh && asdf plugin-add python https://github.com/asdf-vm/asdf-python.git
  args:
    creates: "{{ lookup('env', 'HOME') }}/.asdf/plugins/python"
  environment:
    PATH: "{{ lookup('env', 'PATH') }}:{{ lookup('env', 'HOME') }}/.asdf/bin:{{ lookup('env', 'HOME') }}/.asdf/shims"
  tags: asdf

- name: Install latest Ruby version with ASDF
  shell: asdf install ruby latest
  tags: asdf

- name: Set global Ruby version
  shell: asdf global ruby latest
  tags: asdf

- name: Install latest Node.js version with ASDF
  shell: asdf install nodejs latest
  tags: asdf

- name: Set global Node.js version
  shell: asdf global nodejs latest
  tags: asdf

- name: Install latest Python version with ASDF
  shell: asdf install python latest
  tags: asdf

- name: Set global Python version
  shell: asdf global python latest
  tags: asdf
