- name: Remove conflicting Docker packages
  become: true
  apt:
    name: "{{ item }}"
    state: absent
  loop:
    - docker.io
    - docker-doc
    - podman-docker
    - containerd
    - runc
  tags: docker

- name: Setup Docker Repository and Install
  block:
    - name: Create directory for Docker GPG key
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Add Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: "0644"

    - name: Add Docker APT source list
      shell: |
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
      args:
        creates: /etc/apt/sources.list.d/docker.list

    - name: Install Docker packages
      become: true
      apt:
        name: "{{ docker_packages }}"
        state: present
  tags: docker

- name: Ensure Docker service is running and user is added
  become: true
  block:
    - service:
        name: docker
        state: started
        enabled: true
    - user:
        name: "{{ user }}"
        groups: docker
        append: true
  tags: docker

- name: Download and Install Lazydocker
  become: true
  get_url:
    url: "https://github.com/jesseduffield/lazydocker/releases/download/v0.23.3/lazydocker_0.23.3_Linux_x86_64.tar.gz"
    dest: /tmp/lazydocker.tar.gz
  register: lazydocker_download
  tags: lazydocker

- name: Extract and Install Lazydocker
  become: true
  unarchive:
    src: /tmp/lazydocker.tar.gz
    dest: /usr/local/bin/
    remote_src: yes
  args:
    creates: /usr/local/bin/lazydocker
  when: lazydocker_download.changed
  tags: lazydocker
