- name: Clone .dotfiles
  ansible.builtin.git:
    repo: "git@github.com:{{ github_account }}/.dotfiles.git"
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags: &dotfiles_setup_tags ["install", "dotfiles", "stow"]

- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./bin/setup.zsh
  tags: *dotfiles_setup_tags
