- name: Clone .dotfiles
  ansible.builtin.git:
    repo: "git@github.com:{{ github_account }}/.dotfiles.git"
    dest: "/home/{{ user }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  become: true
  become_user: "{{ user }}"
  tags: &dotfiles_setup_tags ["install", "dotfiles", "stow"]

- name: Stow dotfiles
  shell: "cd /home/{{ user }}/.dotfiles && ./bin/setup.zsh"
  become: true
  become_user: "{{ user }}"
  changed_when: false
  tags: *dotfiles_setup_tags
