- name: Check if project directories exist
  ansible.builtin.stat:
    path: "{{ personal }}/{{ item }}"
  register: repo_dir_check
  loop: "{{ project_repos }}"
  loop_control:
    loop_var: item
    index_var: repo_index
  tags: projects

- name: Clone or update personal repositories
  block:
    - name: Clone the repository if not present
      ansible.builtin.git:
        repo: "git@github.com:{{ github_account }}/{{ item }}.git"
        dest: "{{ personal }}/{{ item }}"
        clone: yes
        update: no
      when: not repo_dir_check.results[repo_index].stat.exists
      loop: "{{ project_repos }}"
      loop_control:
        loop_var: item
        index_var: repo_index
      tags: projects

- name: Pull latest changes if the repository exists
  ansible.builtin.git:
    repo: "git@github.com:{{ github_account }}/{{ item }}.git"
    dest: "{{ personal }}/{{ item }}"
    update: yes
  when: repo_dir_check.results[repo_index].stat.exists
  loop: "{{ project_repos }}"
  loop_control:
    loop_var: item
    index_var: repo_index
  tags: projects
