- name: Add GPG Key and Repository for {{ item.name }}
  become: true
  block:
    - name: Download {{ item.name }} GPG key
      get_url:
        url: "{{ item.gpg_key_url }}"
        dest: "/usr/share/keyrings/{{ item.name }}-archive-keyring.gpg"
        mode: "0644"

    - name: Add {{ item.name }} repository
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/{{ item.name }}-archive-keyring.gpg] {{ item.repo }} {{ item.build }} {{ item.branch }}"
        state: present
        update_cache: true

    - name: Install {{ item.name }}
      apt:
        name: "{{ item.name }}"
        state: present
  tags: repo
