- name: Check if RustDesk is Installed
  become: true
  command: "rustdesk --version"
  register: rustdesk_check
  changed_when: false
  failed_when: rustdesk_check.rc != 0

- name: Download RustDesk .deb Package
  become: true
  get_url:
    url: "https://github.com/rustdesk/rustdesk/releases/download/{{ rustdesk_version }}/rustdesk-{{ rustdesk_version }}-{{ rustdesk_arch }}.deb"
    dest: "/tmp/rustdesk-{{ rustdesk_version }}-{{ rustdesk_arch }}.deb"
    mode: "0644"
  when: rustdesk_check.failed
  tags: *tags_for_rustdesk_tasks

- name: Install RustDesk .deb Package
  become: true
  apt:
    deb: "/tmp/rustdesk-{{ rustdesk_version }}-{{ rustdesk_arch }}.deb"
    state: present
  when: rustdesk_check.failed
  tags: *tags_for_rustdesk_tasks

- name: Verify RustDesk Installation
  become: true
  command: "rustdesk --version"
  register: rustdesk_check
  changed_when: false
  tags: *tags_for_rustdesk_tasks

- name: Clean Up RustDesk .deb Package
  become: true
  file:
    path: "/tmp/rustdesk-{{ rustdesk_version }}-{{ rustdesk_arch }}.deb"
    state: absent
  tags: *tags_for_rustdesk_tasks
