- name: Define RustDesk Variables
  vars:
    rustdesk_version: "1.3.5"
    rustdesk_arch: "x86_64"

- name: Download RustDesk .deb Package
  become: true
  get_url:
    url: "https://github.com/rustdesk/rustdesk/releases/download/{{ rustdesk_version }}/rustdesk-{{ rustdesk_version }}-{{ rustdesk_arch }}.deb"
    dest: "/tmp/rustdesk.deb"
    mode: "0644"
  register: rustdesk_download
  tags: &tags_for_rustdesk_tasks ["install", "rustdesk", "desktop"]

- name: Install RustDesk .deb Package
  become: true
  apt:
    deb: /tmp/rustdesk.deb
    state: present
  when: rustdesk_download.changed
  tags: *tags_for_rustdesk_tasks

- name: Verify RustDesk Installation
  become: true
  command: "rustdesk --version"
  register: rustdesk_check
  changed_when: false
  tags: *tags_for_rustdesk_tasks

- name: Clean Up RustDesk .deb Package
  become: true
  file:
    path: "/tmp/rustdesk.deb"
    state: absent
  tags: *tags_for_rustdesk_tasks
