- name: Ensure .ssh directory exists
  file:
    dest: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory
  tags: ssh

- name: Copy SSH keys
  copy:
    src: "{{ item }}"
    dest: "{{ dest_key if 'pub' not in item else dest_key + '.pub' }}"
    mode: "{{ '0600' if 'pub' not in item else '0644' }}"
  loop:
    - "{{ source_key }}"
    - "{{ source_key }}.pub"
  tags: ssh

- name: Set authorized key from file
  authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_ed25519.pub') }}"
  tags: ssh

- name: Add GitHub to known hosts
  shell: "ssh-keyscan -H github.com >> {{ lookup('env', 'HOME') }}/.ssh/known_hosts"
  args:
    creates: "{{ lookup('env', 'HOME') }}/.ssh/known_hosts"
  tags: ssh
