---
- name: Ensure fonts directory exists
  become: true
  ansible.builtin.file:
    path: "/home/{{ user }}/.local/share/fonts"
    state: directory
    mode: "0755"
    owner: "{{ user }}"
    group: "{{ user }}"
  tags: font

- name: Download Fira Code Mono Nerd Font
  ansible.builtin.get_url:
    url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/FiraCode.zip"
    dest: /tmp/FiraCode.zip
    mode: "0644"
  tags: font

- name: Unzip Fira Code Nerd Font
  become: true
  become_user: "{{ user }}"
  ansible.builtin.unarchive:
    src: /tmp/FiraCode.zip
    dest: "/home/{{ user }}/.local/share/fonts"
    remote_src: true
  tags: font

- name: Refresh font cache
  ansible.builtin.command: fc-cache -fv
  changed_when: false
  tags: font

- name: Remove downloaded font zip file
  ansible.builtin.file:
    path: /tmp/FiraCode.zip
    state: absent
  tags: font
